name: simple-streamlit-app
description: A simple Streamlit app with a button that displays a message
command: [
  "streamlit",
  "run",
  "app.py",
  "--server.port=8000",
  "--server.address=0.0.0.0"
]
